###
POST http://localhost:9191/api/opinion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJub20iOiJVc2VyIiwiZXhwIjoxNzIwNzk0OTk1LCJzdWIiOiJhZG1pbkBnbWFpbC5jb20ifQ.irZy7RGEXdSZL1IgGK_pjtvZwyZiBwWboFSWY42wKVM

{
  "comment" : "Ceci est une opinion avec accès ADMIN et PUBLISHER"
}

###
// Obtenir liste des Opinions VISITOR
GET http://localhost:9191/api/opinion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJkdXJlbGFkaWdAZ21haWwuY29tIiwibm9tIjoiRHVyZWwiLCJleHAiOjE3MjA1NDQyNDd9.6jTmQuRLqi2lm0C88U-wGZSlwuj8xea_s0f1W0HKYbA


###
// Obtenir liste des Opinions ADMIN
GET http://localhost:9191/api/opinion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJub20iOiJVc2VyIiwiZXhwIjoxNzIwNzk0OTk1LCJzdWIiOiJhZG1pbkBnbWFpbC5jb20ifQ.irZy7RGEXdSZL1IgGK_pjtvZwyZiBwWboFSWY42wKVM


###
// Obtenir liste des Opinions PUBLISHER
GET http://localhost:9191/api/opinion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwdWJsaXNoZXJAZ21haWwuY29tIiwibm9tIjoiVXNlciBQdWJsaXNoZXIiLCJleHAiOjE3MjA1NDM5NDd9.dfT3iiG0S7Da7cvnNHVHN4nm1SOQx1NteCLI8AS7dK8

