###
// Registration
POST http://localhost:9191/api/register
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "ADMIN",
  "email": "admin@gmail.com",
  "password": "admin",
  "phoneNumber": "0656575859"
}


###
// Activation
POST http://localhost:9191/api/activationCode
Content-Type: application/json

{
  "code": "653519"
}


###
// login
POST http://localhost:9191/api/login
Content-Type: application/json

{
  "username": "dureladig@gmail.com",
  "password": "pwd"
}

###
// login admin
POST http://localhost:9191/api/login
Content-Type: application/json

{
  "username": "admin@gmail.com",
  "password": "admin"
}

###
// login publisher
POST http://localhost:9191/api/login
Content-Type: application/json

{
  "username": "publisher@gmail.com",
  "password": "admin"
}


###
// Obtenir des ADMIN connectés
GET http://localhost:9191/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJub20iOiJVc2VyIiwiZXhwIjoxNzIwNzk0OTk1LCJzdWIiOiJhZG1pbkBnbWFpbC5jb20ifQ.irZy7RGEXdSZL1IgGK_pjtvZwyZiBwWboFSWY42wKVM


###
// Obtenir liste des Opinions PUBLISHER
GET http://localhost:9191/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwdWJsaXNoZXJAZ21haWwuY29tIiwibm9tIjoiVXNlciBQdWJsaXNoZXIiLCJleHAiOjE3MjA1NDM5NDd9.dfT3iiG0S7Da7cvnNHVHN4nm1SOQx1NteCLI8AS7dK8

