package com.romeoDjoman.inscicecom.ennum;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum PermissionType {


    // User permissions
    USER_SEARCH_PUBLICATIONS,
    USER_FILTER_PUBLICATIONS,
    USER_VIEW_LATEST_PUBLICATIONS,
    USER_VIEW_TOP_SALES,
    USER_VIEW_TOP_RATED,
    USER_VIEW_PUBLICATION_DETAIL,
    USER_AUTHENTICATE,
    USER_REGISTER,

    // Customer permissions
    CUSTOMER_ADD_TO_CART,
    CUSTOMER_VIEW_CART,
    CUSTOMER_REMOVE_FROM_CART,
    CUSTOMER_CLEAR_CART,
    CUSTOMER_PROCESS_PAYMENT,
    CUSTOMER_MANAGE_PROFILE,
    CUSTOMER_VIEW_ORDER_HISTORY,
    CUSTOMER_VIEW_SUBSCRIPTION,
    CUSTOMER_CANCEL_SUBSCRIPTION,
    CUSTOMER_RENEW_SUBSCRIPTION,
    CUSTOMER_VIEW_ORDER_DETAIL,

    // Contributor permissions
    CONTRIBUTOR_VIEW_PENDING_CONTRIBUTIONS,

    // Publisher permissions
    PUBLISHER_CREATE_PUBLICATION,
    PUBLISHER_VIEW_SUBMITTED_PUBLICATIONS,
    PUBLISHER_VIEW_VALIDATED_PUBLICATIONS,
    PUBLISHER_VIEW_CONTRIBUTOR_RESPONSES,
    PUBLISHER_COMMUNICATE_WITH_CONTRIBUTORS,
    PUBLISHER_VIEW_SUBMITTED,
    PUBLISHER_VIEW_NON_SUBMITTED,
    PUBLISHER_VIEW_VALIDATED,
    PUBLISHER_REVISE_PUBLICATION,
    PUBLISHER_SUBMIT_FOR_REVIEW,
    PUBLISHER_SUBMIT_FINAL,

    // Administrator permissions
    ADMINISTRATOR_VIEW_SUBMITTED_PUBLICATIONS,
    ADMINISTRATOR_VIEW_PUBLICATION_DETAIL,
    ADMINISTRATOR_MANAGE_CUSTOMERS,
    ADMINISTRATOR_CREATE_CONTRIBUTOR,
    ADMINISTRATOR_UPDATE_CONTRIBUTOR,
    ADMINISTRATOR_DEACTIVATE_CONTRIBUTOR;

    @Getter
    private final String label = name();

}
